last_change = 2026-08-14T15:51:35.099427Z
addr = 0x27d90
size = 0x473
name = "CDemoPlayer_StopPlayback"
type = "void"

[header]
name = "CDemoPlayer_StopPlayback"
addr = 0x27d90
type = "void"

[header.args]
