last_change = 2026-08-14T15:51:35.099507Z
addr = 0x74c60
size = 0x1b
name = "CEngineClient_IsPlayingDemo"
type = "char"

[header]
name = "CEngineClient_IsPlayingDemo"
addr = 0x74c60
type = "char"

[header.args]
