last_change = 2026-08-14T15:51:35.099496Z
addr = 0x74390
size = 0x11
name = "CEngineClient_DumpNetStats"
type = "void"

[header]
name = "CEngineClient_DumpNetStats"
addr = 0x74390
type = "void"

[header.args]
