last_change = 2026-08-14T15:51:35.099509Z
addr = 0x750f0
size = 0x8
name = "CEngineServer_GetAchievementMgr"
type = "long long"

[header]
name = "CEngineServer_GetAchievementMgr"
addr = 0x750f0
type = "long long"

[header.args]
