last_change = 2026-08-14T15:51:35.099564Z
addr = 0x9f2d0
size = 0x85
name = "CEngineServer_SetFakeClientConVarValue"

[header]
name = "CEngineServer_SetFakeClientConVarValue"
addr = 0x9f2d0

[header.args]
