last_change = 2026-08-14T15:51:35.099546Z
addr = 0x9de60
size = 0x132
name = "CNetworkGameServer_DirectUpdate"
type = "_UNKNOWN **"

[header]
name = "CNetworkGameServer_DirectUpdate"
addr = 0x9de60
type = "_UNKNOWN **"

[header.args]
