last_change = 2026-08-14T15:51:35.099559Z
addr = 0x9f080
size = 0x63
name = "CEngineServer_GetPlayerNetworkIDString"

[header]
name = "CEngineServer_GetPlayerNetworkIDString"
addr = 0x9f080

[header.args]
