last_change = 2026-08-14T15:51:35.099621Z
addr = 0xadb40
size = 0x4d8
name = "CNetworkGameServerBase_Shutdown"
type = "unsigned long long *"

[header]
name = "CNetworkGameServerBase_Shutdown"
addr = 0xadb40
type = "unsigned long long *"

[header.args]
