last_change = 2026-08-14T15:51:35.099606Z
addr = 0xa9e10
size = 0xb3d
name = "CNetworkGameServerBase_FillKV3ServerInfo"
type = "double"

[header]
name = "CNetworkGameServerBase_FillKV3ServerInfo"
addr = 0xa9e10
type = "double"

[header.args]
