last_change = 2026-08-14T15:51:35.099645Z
addr = 0xb3740
size = 0x274
name = "CNetworkGameServerBase_ServerAdvanceTick"

[header]
name = "CNetworkGameServerBase_ServerAdvanceTick"
addr = 0xb3740

[header.args]
