last_change = 2026-08-14T15:51:35.099687Z
addr = 0xc9430
size = 0xea
name = "CServerSideClientBase_GetUserIDString"
type = "CUtlString *"

[header]
name = "CServerSideClientBase_GetUserIDString"
addr = 0xc9430
type = "CUtlString *"

[header.args]
