last_change = 2026-08-14T15:51:35.099702Z
addr = 0xfdb10
size = 0x39
name = "CEngineSoundServices_ShouldSuppressNonUISounds"

[header]
name = "CEngineSoundServices_ShouldSuppressNonUISounds"
addr = 0xfdb10

[header.args]
