last_change = 2026-08-14T15:51:35.099771Z
addr = 0x1cf3f0
size = 0x3de
name = "CGameClientConnectPrerequisite_ctor"

[header]
name = "CGameClientConnectPrerequisite_ctor"
addr = 0x1cf3f0

[header.args]
