last_change = 2026-08-14T15:51:35.099767Z
addr = 0x1c8e50
size = 0x2a6
name = "CMapListService_IsMapValid"
type = "char"

[header]
name = "CMapListService_IsMapValid"
addr = 0x1c8e50
type = "char"

[header.args]
