last_change = 2026-08-14T15:51:35.099837Z
addr = 0x1d4b20
size = 0xaf
name = "CNetworkClientService_SendNetMessage"
type = "char"

[header]
name = "CNetworkClientService_SendNetMessage"
addr = 0x1d4b20
type = "char"

[header.args]
