last_change = 2026-08-14T15:51:35.099853Z
addr = 0x1ddd90
size = 0x14
name = "CNetworkServerService_OnServerAdvanceTick"

[header]
name = "CNetworkServerService_OnServerAdvanceTick"
addr = 0x1ddd90

[header.args]
