last_change = 2026-08-14T14:22:53.185499Z
addr = 0x1deec0
size = 0x14e
name = "CNetworkServerService_OnSimpleLoopFrameUpdate"
type = "long long"

[header]
name = "CNetworkServerService_OnSimpleLoopFrameUpdate"
addr = 0x1deec0
type = "long long"

[header.args]
