last_change = 2026-08-14T15:51:35.099820Z
addr = 0x1d3910
size = 0x396
name = "CNetworkClientService_PrintConnectionStatus"

[header]
name = "CNetworkClientService_PrintConnectionStatus"
addr = 0x1d3910

[header.args]
