last_change = 2026-08-14T15:51:35.099915Z
addr = 0x21b660
size = 0x22f
name = "CLoopTypeBase_LoadDependentServices"

[header]
name = "CLoopTypeBase_LoadDependentServices"
addr = 0x21b660

[header.args]
