last_change = 2026-08-14T15:51:35.099935Z
addr = 0x223600
size = 0x13f
name = "CLoopTypeClientServer_DeactivateLoop"

[header]
name = "CLoopTypeClientServer_DeactivateLoop"
addr = 0x223600

[header.args]
