last_change = 2026-08-14T15:51:35.099943Z
addr = 0x2307b0
size = 0x9c
name = "CLoopTypeSimpleService_OnLoopActivate"
type = "long long"

[header]
name = "CLoopTypeSimpleService_OnLoopActivate"
addr = 0x2307b0
type = "long long"

[header.args]
