[0x23bf60]
addr = 0x23bf60
func_addr = 0x23bf60
comment = "Microsoft VisualC v7/14 64bit runtime"
decompiled = false

[0x33293]
addr = 0x33293
func_addr = 0x32cc0
comment = "Trap to Debugger"
decompiled = false

[0x45a4b]
addr = 0x45a4b
func_addr = 0x458b0
comment = "Trap to Debugger"
decompiled = false

[0x45aeb]
addr = 0x45aeb
func_addr = 0x458b0
comment = "Trap to Debugger"
decompiled = false

[0x45e1b]
addr = 0x45e1b
func_addr = 0x45da0
comment = "Trap to Debugger"
decompiled = false

[0x45e57]
addr = 0x45e57
func_addr = 0x45da0
comment = "Trap to Debugger"
decompiled = false

[0x461da]
addr = 0x461da
func_addr = 0x460c0
comment = "Trap to Debugger"
decompiled = false

[0x4777b]
addr = 0x4777b
func_addr = 0x46cb0
comment = "void (__cdecl *)()"
decompiled = false

[0x5cd26]
addr = 0x5cd26
func_addr = 0x5ca30
comment = "Trap to Debugger"
decompiled = false

[0x5f7c0]
addr = 0x5f7c0
func_addr = 0x5f740
comment = "switch 7 cases"
decompiled = false
