[0x23bf60]
addr = 0x23bf60
func_addr = 0x23bf60
comment = "Microsoft VisualC v7/14 64bit runtime"
decompiled = false

[0x33293]
addr = 0x33293
func_addr = 0x32cc0
comment = "Trap to Debugger"
decompiled = false

[0x45a4b]
addr = 0x45a4b
func_addr = 0x458b0
comment = "Trap to Debugger"
decompiled = false

[0x45aeb]
addr = 0x45aeb
func_addr = 0x458b0
comment = "Trap to Debugger"
decompiled = false

[0x45e1b]
addr = 0x45e1b
func_addr = 0x45da0
comment = "Trap to Debugger"
decompiled = false

[0x45e57]
addr = 0x45e57
func_addr = 0x45da0
comment = "Trap to Debugger"
decompiled = false

[0x461da]
addr = 0x461da
func_addr = 0x460c0
comment = "Trap to Debugger"
decompiled = false

[0x4777b]
addr = 0x4777b
func_addr = 0x46cb0
comment = "void (__cdecl *)()"
decompiled = false

[0x5cd26]
addr = 0x5cd26
func_addr = 0x5ca30
comment = "Trap to Debugger"
decompiled = false

[0x5f7c0]
addr = 0x5f7c0
func_addr = 0x5f740
comment = "switch 7 cases"
decompiled = false

[0x5f7de]
addr = 0x5f7de
func_addr = 0x5f740
comment = "switch jump"
decompiled = false

[0x5f7e0]
addr = 0x5f7e0
func_addr = 0x5f740
comment = "jumptable 00000001800607DE case 1"
decompiled = false

[0x5f7f9]
addr = 0x5f7f9
func_addr = 0x5f740
comment = "jumptable 00000001800607DE case 2"
decompiled = false

[0x5f988]
addr = 0x5f988
func_addr = 0x5f740
comment = "jumptable 00000001800607DE case 3"
decompiled = false

[0x5f9da]
addr = 0x5f9da
func_addr = 0x5f740
comment = "jumptable 00000001800607DE case 4"
decompiled = false

[0x5f9f3]
addr = 0x5f9f3
func_addr = 0x5f740
comment = "jumptable 00000001800607DE case 5"
decompiled = false

[0x5fa1e]
addr = 0x5fa1e
func_addr = 0x5f740
comment = "jumptable 00000001800607DE case 6"
decompiled = false

[0x5fa58]
addr = 0x5fa58
func_addr = 0x5f740
comment = "jumptable 00000001800607DE case 7"
decompiled = false

[0x5fc77]
addr = 0x5fc77
func_addr = 0x5f740
comment = "jumptable 00000001800607DE default case"
decompiled = false

[0x5ff0c]
addr = 0x5ff0c
func_addr = 0x5f740
comment = "jump table for switch statement"
decompiled = false

[0x63e17]
addr = 0x63e17
func_addr = 0x638c0
comment = "Trap to Debugger"
decompiled = false

[0x9fbaa]
addr = 0x9fbaa
func_addr = 0x9fb70
comment = "Trap to Debugger"
decompiled = false

[0x9fbb8]
addr = 0x9fbb8
func_addr = 0x9fb70
comment = "Trap to Debugger"
decompiled = false

[0xae631]
addr = 0xae631
func_addr = 0xae550
comment = "Trap to Debugger"
decompiled = false

[0xb357c]
addr = 0xb357c
func_addr = 0xb34a0
comment = "this"
decompiled = false

[0x1c2c69]
addr = 0x1c2c69
func_addr = 0x1c2850
comment = "Trap to Debugger"
decompiled = false

[0x1d09da]
addr = 0x1d09da
func_addr = 0x1d0030
comment = "void (__cdecl *)()"
decompiled = false

[0x1d0a31]
addr = 0x1d0a31
func_addr = 0x1d0030
comment = "void (__cdecl *)()"
decompiled = false

[0x1d0a88]
addr = 0x1d0a88
func_addr = 0x1d0030
comment = "void (__cdecl *)()"
decompiled = false

[0x1d0adf]
addr = 0x1d0adf
func_addr = 0x1d0030
comment = "void (__cdecl *)()"
decompiled = false

[0x1d0b36]
addr = 0x1d0b36
func_addr = 0x1d0030
comment = "void (__cdecl *)()"
decompiled = false

[0x1d0b8d]
addr = 0x1d0b8d
func_addr = 0x1d0030
comment = "void (__cdecl *)()"
decompiled = false

[0x1d0be4]
addr = 0x1d0be4
func_addr = 0x1d0030
comment = "void (__cdecl *)()"
decompiled = false

[0x1d0c3b]
addr = 0x1d0c3b
func_addr = 0x1d0030
comment = "void (__cdecl *)()"
decompiled = false

[0x1d0c92]
addr = 0x1d0c92
func_addr = 0x1d0030
comment = "void (__cdecl *)()"
decompiled = false

[0x1d0ce9]
addr = 0x1d0ce9
func_addr = 0x1d0030
comment = "void (__cdecl *)()"
decompiled = false

[0x1d0d40]
addr = 0x1d0d40
func_addr = 0x1d0030
comment = "void (__cdecl *)()"
decompiled = false

[0x1d0d97]
addr = 0x1d0d97
func_addr = 0x1d0030
comment = "void (__cdecl *)()"
decompiled = false

[0x1dce28]
addr = 0x1dce28
func_addr = 0x1dc530
comment = "void (__cdecl *)()"
decompiled = false

[0x1dce7f]
addr = 0x1dce7f
func_addr = 0x1dc530
comment = "void (__cdecl *)()"
decompiled = false

[0x1dced6]
addr = 0x1dced6
func_addr = 0x1dc530
comment = "void (__cdecl *)()"
decompiled = false

[0x1dcf2d]
addr = 0x1dcf2d
func_addr = 0x1dc530
comment = "void (__cdecl *)()"
decompiled = false

[0x1dcf84]
addr = 0x1dcf84
func_addr = 0x1dc530
comment = "void (__cdecl *)()"
decompiled = false

[0x1dcfdb]
addr = 0x1dcfdb
func_addr = 0x1dc530
comment = "void (__cdecl *)()"
decompiled = false

[0x1dd032]
addr = 0x1dd032
func_addr = 0x1dc530
comment = "void (__cdecl *)()"
decompiled = false

[0x1dd089]
addr = 0x1dd089
func_addr = 0x1dc530
comment = "void (__cdecl *)()"
decompiled = false

[0x1dd0e0]
addr = 0x1dd0e0
func_addr = 0x1dc530
comment = "void (__cdecl *)()"
decompiled = false

[0x1dd137]
addr = 0x1dd137
func_addr = 0x1dc530
comment = "void (__cdecl *)()"
decompiled = false

[0x1dd18e]
addr = 0x1dd18e
func_addr = 0x1dc530
comment = "void (__cdecl *)()"
decompiled = false

[0x1f1e00]
addr = 0x1f1e00
func_addr = 0x1f1ad0
comment = "void (__cdecl *)()"
decompiled = false

[0x202f7f]
addr = 0x202f7f
func_addr = 0x202f40
comment = "Trap to Debugger"
decompiled = false

[0x20ea45]
addr = 0x20ea45
func_addr = 0x20ea00
comment = "Trap to Debugger"
decompiled = false

[0x20ec41]
addr = 0x20ec41
func_addr = 0x20ebb0
comment = "Trap to Debugger"
decompiled = false

[0x20ec72]
addr = 0x20ec72
func_addr = 0x20ebb0
comment = "Trap to Debugger"
decompiled = false

[0x20ee90]
addr = 0x20ee90
func_addr = 0x20ebb0
comment = "Trap to Debugger"
decompiled = false

[0x20f0ac]
addr = 0x20f0ac
func_addr = 0x20f050
comment = "Trap to Debugger"
decompiled = false

[0x21075a]
addr = 0x21075a
func_addr = 0x210080
comment = "th32ProcessID"
decompiled = false

[0x21075c]
addr = 0x21075c
func_addr = 0x210080
comment = "dwFlags"
decompiled = false

[0x210786]
addr = 0x210786
func_addr = 0x210080
comment = "lppe"
decompiled = false

[0x210797]
addr = 0x210797
func_addr = 0x210080
comment = "hSnapshot"
decompiled = false

[0x2107c8]
addr = 0x2107c8
func_addr = 0x210080
comment = "dwProcessId"
decompiled = false
