[0x482830]
last_change = 2026-08-14T15:06:42.195755Z
addr = 0x482830
name = "Plat_EventWriteTransfer"
type = "long long __fastcall(unsigned long long, unsigned long long)"
size = 0x8

[0x688ca0]
addr = 0x688ca0
name = "unk_180689CA0"
size = 0x1

[0x688cb0]
addr = 0x688cb0
name = "unk_180689CB0"
size = 0x1

[0x688cf8]
addr = 0x688cf8
name = "qword_180689CF8"
size = 0x8

[0x688d60]
addr = 0x688d60
name = "unk_180689D60"
size = 0x1

[0x688d70]
addr = 0x688d70
name = "unk_180689D70"
size = 0x1

[0x688dc0]
addr = 0x688dc0
name = "qword_180689DC0"
size = 0x8

[0x688dc8]
addr = 0x688dc8
name = "qword_180689DC8"
size = 0x8

[0x688dd0]
addr = 0x688dd0
name = "qword_180689DD0"
size = 0x8

[0x4d0220]
addr = 0x4d0220
name = "g_pInterfaceGlobals"
size = 0x8

[0x687b00]
addr = 0x687b00
name = "g_pVApplication"
size = 0x8

[0x687b08]
addr = 0x687b08
name = "g_pVEngineCvar"
size = 0x8

[0x687b10]
addr = 0x687b10
name = "g_pVStringTokenSystem"
size = 0x1

[0x687b18]
addr = 0x687b18
name = "g_pProcessUtils"
size = 0x1

[0x687b20]
addr = 0x687b20
name = "g_pHelpSystem"
size = 0x1

[0x687b28]
addr = 0x687b28
name = "g_pToolSceneNodeFactory"
size = 0x1

[0x687b30]
addr = 0x687b30
name = "g_pEconItemToolModel"
size = 0x1

[0x687b38]
addr = 0x687b38
name = "g_pSchemaTestExternalTwo"
size = 0x1

[0x687b40]
addr = 0x687b40
name = "g_pSchemaTestExternalOne"
size = 0x1

[0x687b48]
addr = 0x687b48
name = "g_pAnimationSystem"
size = 0x8

[0x687b50]
addr = 0x687b50
name = "g_pAnimationSystemUtils"
size = 0x1

[0x687b58]
addr = 0x687b58
name = "g_pTestScriptMgr"
size = 0x8
