[0x482830]
last_change = 2026-08-14T15:06:42.195755Z
addr = 0x482830
name = "Plat_EventWriteTransfer"
type = "long long __fastcall(unsigned long long, unsigned long long)"
size = 0x8

[0x688ca0]
addr = 0x688ca0
name = "unk_180689CA0"
size = 0x1

[0x688cb0]
addr = 0x688cb0
name = "unk_180689CB0"
size = 0x1

[0x688cf8]
addr = 0x688cf8
name = "qword_180689CF8"
size = 0x8

[0x688d60]
addr = 0x688d60
name = "unk_180689D60"
size = 0x1

[0x688d70]
addr = 0x688d70
name = "unk_180689D70"
size = 0x1

[0x688dc0]
addr = 0x688dc0
name = "qword_180689DC0"
size = 0x8

[0x688dc8]
addr = 0x688dc8
name = "qword_180689DC8"
size = 0x8

[0x688dd0]
addr = 0x688dd0
name = "qword_180689DD0"
size = 0x8

[0x4d0220]
addr = 0x4d0220
name = "g_pInterfaceGlobals"
size = 0x8

[0x687b00]
addr = 0x687b00
name = "g_pVApplication"
size = 0x8

[0x687b08]
addr = 0x687b08
name = "g_pVEngineCvar"
size = 0x8

[0x687b10]
addr = 0x687b10
name = "g_pVStringTokenSystem"
size = 0x1

[0x687b18]
addr = 0x687b18
name = "g_pProcessUtils"
size = 0x1

[0x687b20]
addr = 0x687b20
name = "g_pHelpSystem"
size = 0x1

[0x687b28]
addr = 0x687b28
name = "g_pToolSceneNodeFactory"
size = 0x1

[0x687b30]
addr = 0x687b30
name = "g_pEconItemToolModel"
size = 0x1

[0x687b38]
addr = 0x687b38
name = "g_pSchemaTestExternalTwo"
size = 0x1

[0x687b40]
addr = 0x687b40
name = "g_pSchemaTestExternalOne"
size = 0x1

[0x687b48]
addr = 0x687b48
name = "g_pAnimationSystem"
size = 0x8

[0x687b50]
addr = 0x687b50
name = "g_pAnimationSystemUtils"
size = 0x1

[0x687b58]
addr = 0x687b58
name = "g_pTestScriptMgr"
size = 0x8

[0x687b60]
addr = 0x687b60
name = "g_pModelProcessingServices"
size = 0x1

[0x687b68]
addr = 0x687b68
name = "g_pLocalize"
size = 0x8

[0x687b70]
addr = 0x687b70
name = "g_pMaterialUtils"
size = 0x8

[0x687b78]
addr = 0x687b78
name = "g_pFontManager"
size = 0x1

[0x687b80]
addr = 0x687b80
name = "g_pTextLayout"
size = 0x1

[0x687b88]
addr = 0x687b88
name = "g_pAssetRenameSystem"
size = 0x1

[0x687b90]
addr = 0x687b90
name = "g_pAssetPreviewSystem"
size = 0x1

[0x687b98]
addr = 0x687b98
name = "g_pAssetBrowserSystem"
size = 0x1

[0x687ba0]
addr = 0x687ba0
name = "g_pRenderDeviceMgr"
size = 0x8

[0x687ba8]
addr = 0x687ba8
name = "g_pFileSystem"
size = 0x8

[0x687bb0]
addr = 0x687bb0
name = "g_pAsyncFileSystem"
size = 0x8

[0x687bb8]
addr = 0x687bb8
name = "g_pAssetSystem"
size = 0x8

[0x687bc0]
addr = 0x687bc0
name = "g_pAssetSystemTest"
size = 0x1

[0x687bc8]
addr = 0x687bc8
name = "g_pPropertyEditorSystem"
size = 0x1

[0x687bd0]
addr = 0x687bd0
name = "g_pSchemaSystem"
size = 0x8

[0x687bd8]
addr = 0x687bd8
name = "g_pResourceCompilerSystem"
size = 0x1

[0x687be0]
addr = 0x687be0
name = "g_pResourceSystem"
size = 0x8

[0x687be8]
addr = 0x687be8
name = "g_pResourceHandleUtils"
size = 0x8

[0x687bf0]
addr = 0x687bf0
name = "g_pResourceManifestRegistry"
size = 0x8

[0x687bf8]
addr = 0x687bf8
name = "g_pMaterialSystem2"
size = 0x8

[0x687c00]
addr = 0x687c00
name = "g_pPostProcessingSystem"
size = 0x8

[0x687c08]
addr = 0x687c08
name = "g_pInputSystem"
size = 0x8

[0x687c10]
addr = 0x687c10
name = "g_pInputStackSystem"
size = 0x8

[0x687c18]
addr = 0x687c18
name = "g_pVP4"
size = 0x8

[0x687c20]
addr = 0x687c20
name = "g_pMatchFramework"
size = 0x8

[0x687c28]
addr = 0x687c28
name = "g_pVConComm"
size = 0x8

[0x687c30]
addr = 0x687c30
name = "g_pSource2V8System"
size = 0x8

[0x687c38]
addr = 0x687c38
name = "g_pPanoramaUIEngine"
size = 0x8

[0x687c40]
addr = 0x687c40
name = "g_pPanoramaUIClient"
size = 0x8

[0x687c48]
addr = 0x687c48
name = "g_pPanoramaTextServices"
size = 0x1

[0x687c58]
addr = 0x687c58
name = "g_pModelDocUtils"
size = 0x1

[0x687c60]
addr = 0x687c60
name = "g_pAnimGraphEditorUtils"
size = 0x1

[0x687c68]
addr = 0x687c68
name = "g_pRenderDevice"
size = 0x8

[0x687c70]
addr = 0x687c70
name = "g_pRenderDeviceSetup"
size = 0x1

[0x687c78]
addr = 0x687c78
name = "g_pRenderHardwareConfig"
size = 0x8

[0x687c80]
addr = 0x687c80
name = "g_pRenderUtils"
size = 0x1

[0x687c88]
addr = 0x687c88
name = "g_pSoundSystem"
size = 0x8

[0x687c90]
addr = 0x687c90
name = "g_pSoundOpSystemEdit"
size = 0x1

[0x687c98]
addr = 0x687c98
name = "g_pSoundOpSystem"
size = 0x8

[0x687ca0]
addr = 0x687ca0
name = "g_pSteamAudio"
size = 0x1

[0x687ca8]
addr = 0x687ca8
name = "g_pMeshSystem"
size = 0x1

[0x687cb0]
addr = 0x687cb0
name = "g_pMeshUtils"
size = 0x1

[0x687cb8]
addr = 0x687cb8
name = "g_pSceneSystem"
size = 0x8

[0x687cc0]
addr = 0x687cc0
name = "g_pIPulseSystem"
size = 0x8

[0x687cc8]
addr = 0x687cc8
name = "g_pSceneUtils"
size = 0x8

[0x687cd0]
addr = 0x687cd0
name = "g_pScriptManager"
size = 0x1

[0x687cd8]
addr = 0x687cd8
name = "g_pWEBM"
size = 0x8

[0x687ce0]
addr = 0x687ce0
name = "g_pMediaFoundation"
size = 0x8

[0x687ce8]
addr = 0x687ce8
name = "g_pAVI"
size = 0x8
